### ISSUE TITLE
Consistently missing udata from server when stopping and resuming

### ISSUE THREAD

**Issue by kcalvinalvin** [mit-dci/utreexo#216]
On master, I get this message when syncing both the client.

```
panic: uData missing utxo data for block 47413

goroutine 66 [running]:
github.com/mit-dci/utreexo/csn.(*Csn).IBDThread(0xc00000c1e0, 0xc000524000, 0xffffffffffffffff)
        /home/calvin/bitcoin-projects/go/utreexo/go/src/github.com/mit-dci/utreexo/csn/ibd.go:59 +0xbe5
created by github.com/mit-dci/utreexo/csn.(*Csn).Start
        /home/calvin/bitcoin-projects/go/utreexo/go/src/github.com/mit-dci/utreexo/csn/init.go:102 +0x275
```

block 47413 was the block that was stopped and resumed from the server side.

**Comment by kcalvinalvin** [comment]
From more digging, I'm finding out that the forest save/restore isn't working quite right. Forest differs when restarted
