### ISSUE TITLE
Keeps crashing while trying to resume the server

### ISSUE THREAD

**Issue by HalFinneyIsMyHomeBoy** [mit-dci/utreexo#359]
Ran utreexoserver for about an hour,  until it stopped here.  I have an almost fully synced testnet node (at 99.9306%).  

> Finished block 2190000 of max 2541937
> Finished block 2191000 of max 2541937
> Finished block 2192000 of max 2541937
> Finished block 2193000 of max 2541937
> panic: writeTTLs Wanted to overwrite byte 659451172 with 0000ce8c but 0000002a was already there. desth 2193265 createh 2140389 idxinblk 34466
> goroutine 38 [running]:
> github.com/mit-dci/utreexo/bridgenode.flatFileWorkerTTL(_, _, {{{0xc00001a1b0, 0x28}, {0xc0000200c0, 0x37}, {0xc00017e230, 0x46}}, {{0xc00001a1e0, 0x27}, ...}, ...}, ...)
>         /home/owner/utreexo/bridgenode/flatfileworker.go:181 +0x311
> created by github.com/mit-dci/utreexo/bridgenode.BuildProofs
>         /home/owner/utreexo/bridgenode/genproofs.go:110 +0x60a

When trying to resume, I keep getting the error below.  My default directory is  /home/owner/.bitcoin/testnet3/blocks.   However there is no "forestdata" directory there.

> owner@owner-lnd:~/utreexo/cmd/utreexoserver$ ./utreexoserver
> Has access to forest, resuming
> BuildProofs error: initialization error: restoreForest error: open /home/owner/.utreexo/testnet3/forestdata/miscforestfile.dat: no such file or directory.  If your .blk and .dat files are not in /home/owner/.bitcoin/testnet3/blocks, specify alternate path with -datadir
> .

**Comment by kcalvinalvin** [comment]
This repo is unmaintained. Try github.com/utreexo/utreexod
